name: numix-icon-theme-circle
title: Numix Circle Icons
#adopt-info: numix-icon-theme-circle
version: '25.01.31'
summary: Circle is an app icon theme for Linux from the Numix project
description: |
  A Snap for the Numix Circle icon theme.

build-base: core20
base: bare
grade: stable
confinement: strict
license: GPL-3.0

architectures:
  - build-on: amd64
    run-on: all

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Numix-Circle
        - $SNAP/share/icons/Numix-Circle-Light

parts:
  icons:
    after:
      - utils
    plugin: dump
    source: "https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz"
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons
        mv $SNAPCRAFT_PART_INSTALL/usr/share/icons/Numix* $SNAPCRAFT_PART_INSTALL/share/icons/
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Numix-Circle*
      
#    override-pull: |
#      snapcraftctl pull
#      snapcraftctl set-version "$(curl -sL https://api.github.com/repos/numixproject/numix-icon-theme-circle/releases |  jq .[].tag_name -r | grep -v rc | sort -r | head -n 1 | cut -d "-" -f2)"      

  
  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
